### ISSUE TITLE
influxdb/1.2/alpine gpg: keyserver receive failed

### ISSUE THREAD

**Issue by v-raptor** [influxdata/influxdata-docker#79] opened 2017-04-20 04:56 UTC
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
gpg: directory '/root/.gnupg' created
gpg: new configuration file '/root/.gnupg/dirmngr.conf' created
gpg: new configuration file '/root/.gnupg/gpg.conf' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: keyserver receive failed: No keyserver available

**Comment by jsternberg** [comment] 2017-04-24 20:30
Is this still happening? I've seen the keyserver have problems in the past. Also, ensure your local installation has access to the internet. If you're on Mac OS X, I've seen `docker-machine` get into a state where the machine has to be restarted after sleeping before. I haven't experienced it for awhile, but I think it's possible.

I'm going to close this for now since we don't control the keyserver and I haven't experienced this issue when building the images. If you have more details with a reproducer, I can reopen and look again.

**Closed by jsternberg** 2017-04-24 20:30 UTC
