### ISSUE TITLE
error="authorization not found"

### ISSUE THREAD

**Issue by madhu-reddy** [influxdata/influxdata-docker#645] opened 2022-09-21 19:54 UTC
Created an influxdb container,
`docker run -p 8086:8086 -d --name influxdb2 -v /home/user/tick-stack/influxdb2:/var/lib/influxdb2 -v /home/user/tick-stack/influxdb2/config:/etc/influxdb2 influxdb:2.4`

```
Config file (/home/user/tick-stack/influxdb2/config/influx-configs)
[default]

url="http://192.168.10.4:8086" 
 token="nlGp2Zyg1Ioi5hAW67Asg_fYYIWmS29XEd25gSINevFqA23xvnRxlTMChciHDIFQqCVvhrsJayDFwQ9dWz3OeA=="
  org="my-org"
  active=true

[logging]
  level = "warn"
```

But I am seeing the following message in the docker logs, not sure whats its all about,

```
ts=2022-09-15T17:03:36.026516Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.026634Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.064739Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.430481Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.497015Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.630071Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.857328Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:36.926554Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:37.545849Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:37.625427Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:37.802857Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"
ts=2022-09-15T17:03:37.839186Z lvl=info msg=Unauthorized log_id=0cxXXy~l000 error="authorization not found"

```

**Comment by madhu-reddy** [comment] 2022-09-21 19:55
Not sure what the issue here is, but when I tried to bind to a different host port (other than 8086), I don’t see these authorized errors anymore.

`docker run -p 8087:8086 -d --name influxdb2 -v /home/user/tick-stack/influxdb2:/var/lib/influxdb2 -v /home/user/tick-stack/influxdb2/config:/etc/influxdb2 influxdb:2.4`

**Comment by powersj** [comment] 2022-10-27 14:18
Thanks for looping back on what the issue is. Since you figured it out I am going to go ahead and close this one.

**Closed by powersj** 2022-10-27 14:18 UTC
